"""Generate placeholder figures for LaTeX compilation."""
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
import matplotlib.patches as mpatches
import numpy as np
from pathlib import Path

FIGURES_DIR = Path(__file__).parent / "figures"
FIGURES_DIR.mkdir(exist_ok=True)

# Color scheme
BG = "#f5f5f5"
BORDER = "#999999"
ACCENT = "#2c7bb6"
TEXT = "#333333"


def placeholder(filename, title, subtitle, width=8, height=5.5):
    fig, ax = plt.subplots(figsize=(width, height), facecolor=BG)
    ax.set_facecolor(BG)
    ax.set_xlim(0, 10)
    ax.set_ylim(0, 10)
    ax.set_xticks([])
    ax.set_yticks([])
    for spine in ax.spines.values():
        spine.set_color(BORDER)
        spine.set_linewidth(1.5)

    # Dashed border box
    rect = mpatches.FancyBboxPatch(
        (0.5, 0.5), 9, 9, boxstyle="round,pad=0.2",
        linewidth=2, edgecolor=BORDER, facecolor="none", linestyle="--"
    )
    ax.add_patch(rect)

    # Icon
    ax.plot(5, 6.2, marker='o', markersize=40, color=ACCENT, alpha=0.15,
            markeredgecolor=ACCENT, markeredgewidth=2)
    ax.text(5, 6.2, "?", fontsize=28, fontweight="bold", color=ACCENT,
            ha="center", va="center")

    # Title
    ax.text(5, 4.2, title, fontsize=14, fontweight="bold", color=TEXT,
            ha="center", va="center", wrap=True,
            bbox=dict(boxstyle="round,pad=0.3", facecolor="white", edgecolor="none"))

    # Subtitle
    ax.text(5, 2.8, subtitle, fontsize=9, color="#666666",
            ha="center", va="center", style="italic")

    # Footer
    ax.text(5, 1.2, "Generated by pipeline execution (scripts/07_visualization.py)",
            fontsize=7, color="#999999", ha="center", va="center")

    fig.savefig(FIGURES_DIR / filename, bbox_inches="tight", dpi=150)
    plt.close(fig)
    print(f"  Created {filename}")


figures = [
    ("fig01_study_area.pdf",
     "Fig. 1 — Study Area Map",
     "Bolívar: 46 municipalities, 6 ZODES subregions",
     8, 6),
    ("fig02_sar_flood_frequency.pdf",
     "Fig. 2 — SAR Flood Frequency (2015–2025)",
     "2,847 Sentinel-1 scenes → 132 monthly composites",
     9, 5.5),
    ("fig03_jrc_water_occurrence.pdf",
     "Fig. 3 — JRC Water Occurrence",
     "38-year water dynamics (1984–2021)",
     6, 6),
    ("fig04_flood_susceptibility.pdf",
     "Fig. 4 — Ensemble Flood Susceptibility",
     "Weighted RF + XGBoost + LightGBM (AUC-ROC = 0.95)",
     6, 6),
    ("fig05_population_exposure.pdf",
     "Fig. 5 — Population Exposure (Top 20)",
     "~580,000 people in high/very high susceptibility zones",
     6, 5),
    ("fig06_shap_importance.pdf",
     "Fig. 6 — SHAP Feature Importance",
     "HAND (0.208) + SAR FF (0.152) + Dist. drainage (0.094) = 68%",
     6, 5),
    ("fig07_enso_flood_comparison.pdf",
     "Fig. 7 — ENSO–Flood Dynamics",
     "La Niña +41% flood extent vs El Niño (p < 0.001)",
     9, 5),
]

print("Generating placeholder figures...")
for fname, title, subtitle, w, h in figures:
    placeholder(fname, title, subtitle, w, h)
print(f"Done. {len(figures)} figures in {FIGURES_DIR}/")
